#!/usr/bin/env bash

function usage() {
  echo "Usage: [<count>]"
  echo ""
  echo "Stash any local changes and then remove <count> commits"
  exit 1
}

COUNT=1

if [ $# -eq 1 ]; then
  if [ $1 -gt 0 ]; then
    COUNT=$1
  else
    usage
  fi
elif [ $# -ne 0 ]; then
  usage
fi

git stash
git reset --hard HEAD~$COUNT
