#!/bin/env bash

echo "# Display Server"
echo $XDG_SESSION_TYPE
echo ""
echo "# Display Driver"
glxinfo | grep vendor
echo ""
echo "# xrandr --listproviders"
xrandr --listproviders
echo ""
echo "# Devices"
lspci | grep VGA || true
lspci | grep 3D || true
