#!/usr/bin/env bash
# sp-fastbazel run bazel incrementally in Polaris

upstream=$1
if [ -z "$upstream" ]; then
  upstream="@{upstream}"
fi

git diff --dirstat=files,0 "$upstream" \
  | sed -E 's,^[ 0-9. ]+% polaris/src,/,g' \
  | xargs sp-bazel-go 
