#!/usr/bin/env bash

set -e

for i in $(seq 1 30); do
  if [ -d ".buildenv" ]; then
    FILE=$(pwd)/.buildenv/bin/activate
    echo $FILE
    exit 0
  fi
  if [ "$(pwd)" == "/" ]; then
    exit 1
  fi
  cd ..
done

exit 1
