#!/usr/bin/env bash
# connect to Rubrik HQ VPN

function usage() {
  echo "Usage: <repo name>"
  echo ""
  echo "Clones a repo from market of the name given."
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

echo "CC2t3Pf9LOOq" | \
  openconnect \
    --protocol=gp vpn-colo.rubrik.com \
    --user=david.terei \
    -b \
    --passwd-on-stdin \
    --pid-file=/tmp/rubrik-vpn.pid
